spring:
  application:
    name: cantor-service
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cantor_service
    password: "root"
    username: "root"

flyway:
  url: jdbc:mysql://localhost:3306/mysql
  schemas: cantor-service
  user: "root"
  password: "root"
